<?php

namespace Database\Seeders;

use App\Models\Tanah;
use Illuminate\Database\Seeder;

class TanahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            [
                'kode_tanah' => 'TN-0001',
                'ns' => 'NS-2026-000001',
                'name' => 'Budi Santoso',
                'luas_tanah' => '250 m2',
                'jenis_sertifikat' => 'SHM',
                'tanggal_terbit' => '2019-06-12',
                'masa_berlaku' => null,
                'alamat' => 'Jl. Melati No. 12',
                'provinsi' => 'Jawa Barat',
                'kabupaten' => 'Bandung',
                'kecamatan' => 'Coblong',
                'desa' => 'Dago',
                'kode_pos' => '40135',
                'latitude' => -8.833186355,
                'longitude' => 115.14270298,
                'status_tanah' => 'aktif',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0002',
                'ns' => 'NS-2026-000002',
                'name' => 'Siti Aminah',
                'luas_tanah' => '180 m2',
                'jenis_sertifikat' => 'HGB',
                'tanggal_terbit' => '2021-01-05',
                'masa_berlaku' => '2041-01-05',
                'alamat' => 'Komplek Anggrek Blok B2',
                'provinsi' => 'DKI Jakarta',
                'kabupaten' => 'Jakarta Selatan',
                'kecamatan' => 'Kebayoran Baru',
                'desa' => 'Gandaria Utara',
                'kode_pos' => '12140',
                'latitude' => -8.6212,
                'longitude' => 115.0868,
                'status_tanah' => 'aktif',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0003',
                'ns' => 'NS-2026-000003',
                'name' => 'Andi Pratama',
                'luas_tanah' => '320 m2',
                'jenis_sertifikat' => 'HP',
                'tanggal_terbit' => '2020-10-20',
                'masa_berlaku' => '2030-10-20',
                'alamat' => 'Jl. Kenanga No. 8',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Semarang',
                'kecamatan' => 'Tembalang',
                'desa' => 'Bulusan',
                'kode_pos' => '50277',
                'latitude' => -8.6705,
                'longitude' => 115.2126,
                'status_tanah' => 'sengketa',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0004',
                'ns' => 'NS-2026-000004',
                'name' => 'Dewi Lestari',
                'luas_tanah' => '500 m2',
                'jenis_sertifikat' => 'HGU',
                'tanggal_terbit' => '2018-03-15',
                'masa_berlaku' => '2043-03-15',
                'alamat' => 'Kawasan Industri KM 7',
                'provinsi' => 'Banten',
                'kabupaten' => 'Tangerang',
                'kecamatan' => 'Cikupa',
                'desa' => 'Pasir Jaya',
                'kode_pos' => '15710',
                'latitude' => -8.7177,
                'longitude' => 115.1682,
                'status_tanah' => 'dijual',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0005',
                'ns' => 'NS-2026-000005',
                'name' => 'Rudi Hartono',
                'luas_tanah' => '95 m2',
                'jenis_sertifikat' => 'SHM',
                'tanggal_terbit' => '2022-08-09',
                'masa_berlaku' => null,
                'alamat' => 'Perumahan Griya Asri No. 5',
                'provinsi' => 'Jawa Timur',
                'kabupaten' => 'Surabaya',
                'kecamatan' => 'Sukolilo',
                'desa' => 'Keputih',
                'kode_pos' => '60111',
                'latitude' => -8.6478,
                'longitude' => 115.1385,
                'status_tanah' => 'aktif',
                'link_map' => null,
            ],

            [
                'kode_tanah' => 'TN-0006',
                'ns' => 'NS-2026-000006',
                'name' => 'Ahmad Fauzi',
                'luas_tanah' => '210 m2',
                'jenis_sertifikat' => 'SHM',
                'tanggal_terbit' => '2020-02-14',
                'masa_berlaku' => null,
                'alamat' => 'Jl. Sudirman No. 10',
                'provinsi' => 'Sumatera Utara',
                'kabupaten' => 'Medan',
                'kecamatan' => 'Medan Baru',
                'desa' => 'Titi Rantai',
                'kode_pos' => '20153',
                'latitude' => 3.5897,
                'longitude' => 98.6738,
                'status_tanah' => 'aktif',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0007',
                'ns' => 'NS-2026-000007',
                'name' => 'Maya Putri',
                'luas_tanah' => '160 m2',
                'jenis_sertifikat' => 'HGB',
                'tanggal_terbit' => '2021-07-22',
                'masa_berlaku' => '2041-07-22',
                'alamat' => 'Jl. Diponegoro No. 3',
                'provinsi' => 'Sumatera Barat',
                'kabupaten' => 'Padang',
                'kecamatan' => 'Padang Timur',
                'desa' => 'Sawahan',
                'kode_pos' => '25121',
                'latitude' => -0.9492,
                'longitude' => 100.3543,
                'status_tanah' => 'aktif',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0008',
                'ns' => 'NS-2026-000008',
                'name' => 'Rina Sari',
                'luas_tanah' => '275 m2',
                'jenis_sertifikat' => 'SHM',
                'tanggal_terbit' => '2017-11-08',
                'masa_berlaku' => null,
                'alamat' => 'Komplek Melur Blok C1',
                'provinsi' => 'Riau',
                'kabupaten' => 'Pekanbaru',
                'kecamatan' => 'Tampan',
                'desa' => 'Simpang Baru',
                'kode_pos' => '28293',
                'latitude' => 0.5071,
                'longitude' => 101.4478,
                'status_tanah' => 'aktif',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0009',
                'ns' => 'NS-2026-000009',
                'name' => 'Deni Prakoso',
                'luas_tanah' => '340 m2',
                'jenis_sertifikat' => 'HP',
                'tanggal_terbit' => '2019-05-03',
                'masa_berlaku' => '2029-05-03',
                'alamat' => 'Jl. Ahmad Yani No. 21',
                'provinsi' => 'Kepulauan Riau',
                'kabupaten' => 'Batam',
                'kecamatan' => 'Batam Kota',
                'desa' => 'Sungai Panas',
                'kode_pos' => '29444',
                'latitude' => 1.0456,
                'longitude' => 104.0305,
                'status_tanah' => 'aktif',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0010',
                'ns' => 'NS-2026-000010',
                'name' => 'Sri Wahyuni',
                'luas_tanah' => '120 m2',
                'jenis_sertifikat' => 'SHM',
                'tanggal_terbit' => '2022-03-18',
                'masa_berlaku' => null,
                'alamat' => 'Jl. Asia Afrika No. 45',
                'provinsi' => 'Jawa Barat',
                'kabupaten' => 'Bandung',
                'kecamatan' => 'Lengkong',
                'desa' => 'Burangrang',
                'kode_pos' => '40262',
                'latitude' => -6.9219,
                'longitude' => 107.6076,
                'status_tanah' => 'aktif',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0011',
                'ns' => 'NS-2026-000011',
                'name' => 'Bambang Suryo',
                'luas_tanah' => '420 m2',
                'jenis_sertifikat' => 'HGU',
                'tanggal_terbit' => '2016-09-30',
                'masa_berlaku' => '2046-09-30',
                'alamat' => 'Kawasan Perkebunan Blok A',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Solo',
                'kecamatan' => 'Banjarsari',
                'desa' => 'Manahan',
                'kode_pos' => '57139',
                'latitude' => -7.5537,
                'longitude' => 110.8120,
                'status_tanah' => 'dijual',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0012',
                'ns' => 'NS-2026-000012',
                'name' => 'Lukman Hakim',
                'luas_tanah' => '200 m2',
                'jenis_sertifikat' => 'HGB',
                'tanggal_terbit' => '2020-12-01',
                'masa_berlaku' => '2040-12-01',
                'alamat' => 'Jl. Malioboro No. 9',
                'provinsi' => 'DI Yogyakarta',
                'kabupaten' => 'Yogyakarta',
                'kecamatan' => 'Gondomanan',
                'desa' => 'Ngupasan',
                'kode_pos' => '55122',
                'latitude' => -7.7974,
                'longitude' => 110.3705,
                'status_tanah' => 'aktif',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0013',
                'ns' => 'NS-2026-000013',
                'name' => 'Nanda Prameswari',
                'luas_tanah' => '150 m2',
                'jenis_sertifikat' => 'SHM',
                'tanggal_terbit' => '2018-04-27',
                'masa_berlaku' => null,
                'alamat' => 'Jl. Basuki Rahmat No. 17',
                'provinsi' => 'Jawa Timur',
                'kabupaten' => 'Malang',
                'kecamatan' => 'Klojen',
                'desa' => 'Kauman',
                'kode_pos' => '65119',
                'latitude' => -7.9826,
                'longitude' => 112.6308,
                'status_tanah' => 'aktif',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0014',
                'ns' => 'NS-2026-000014',
                'name' => 'I Komang Arya',
                'luas_tanah' => '190 m2',
                'jenis_sertifikat' => 'SHM',
                'tanggal_terbit' => '2019-12-12',
                'masa_berlaku' => null,
                'alamat' => 'Jl. Gatot Subroto No. 6',
                'provinsi' => 'Bali',
                'kabupaten' => 'Denpasar',
                'kecamatan' => 'Denpasar Selatan',
                'desa' => 'Sanur',
                'kode_pos' => '80228',
                'latitude' => -8.7075,
                'longitude' => 115.2625,
                'status_tanah' => 'aktif',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0015',
                'ns' => 'NS-2026-000015',
                'name' => 'Siti Nurhaliza',
                'luas_tanah' => '260 m2',
                'jenis_sertifikat' => 'HP',
                'tanggal_terbit' => '2021-02-10',
                'masa_berlaku' => '2031-02-10',
                'alamat' => 'Jl. Udayana No. 2',
                'provinsi' => 'Nusa Tenggara Barat',
                'kabupaten' => 'Mataram',
                'kecamatan' => 'Cakranegara',
                'desa' => 'Cakra Barat',
                'kode_pos' => '83239',
                'latitude' => -8.5833,
                'longitude' => 116.1167,
                'status_tanah' => 'sengketa',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0016',
                'ns' => 'NS-2026-000016',
                'name' => 'Markus Lado',
                'luas_tanah' => '310 m2',
                'jenis_sertifikat' => 'HGB',
                'tanggal_terbit' => '2020-06-06',
                'masa_berlaku' => '2040-06-06',
                'alamat' => 'Jl. El Tari No. 11',
                'provinsi' => 'Nusa Tenggara Timur',
                'kabupaten' => 'Kupang',
                'kecamatan' => 'Oebobo',
                'desa' => 'Kayu Putih',
                'kode_pos' => '85111',
                'latitude' => -10.1718,
                'longitude' => 123.6070,
                'status_tanah' => 'aktif',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0017',
                'ns' => 'NS-2026-000017',
                'name' => 'Hendra Wijaya',
                'luas_tanah' => '230 m2',
                'jenis_sertifikat' => 'SHM',
                'tanggal_terbit' => '2018-01-19',
                'masa_berlaku' => null,
                'alamat' => 'Jl. Sisingamangaraja No. 18',
                'provinsi' => 'Kalimantan Barat',
                'kabupaten' => 'Pontianak',
                'kecamatan' => 'Pontianak Selatan',
                'desa' => 'Benua Melayu Darat',
                'kode_pos' => '78121',
                'latitude' => -0.0263,
                'longitude' => 109.3425,
                'status_tanah' => 'aktif',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0018',
                'ns' => 'NS-2026-000018',
                'name' => 'Putri Anggraini',
                'luas_tanah' => '180 m2',
                'jenis_sertifikat' => 'SHM',
                'tanggal_terbit' => '2022-09-05',
                'masa_berlaku' => null,
                'alamat' => 'Jl. Ahmad Yani No. 1',
                'provinsi' => 'Kalimantan Selatan',
                'kabupaten' => 'Banjarmasin',
                'kecamatan' => 'Banjarmasin Tengah',
                'desa' => 'Kertak Baru Ilir',
                'kode_pos' => '70111',
                'latitude' => -3.3186,
                'longitude' => 114.5908,
                'status_tanah' => 'aktif',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0019',
                'ns' => 'NS-2026-000019',
                'name' => 'Arif Nugroho',
                'luas_tanah' => '360 m2',
                'jenis_sertifikat' => 'HGU',
                'tanggal_terbit' => '2015-08-17',
                'masa_berlaku' => '2045-08-17',
                'alamat' => 'Kawasan Industri Sungai Kunjang',
                'provinsi' => 'Kalimantan Timur',
                'kabupaten' => 'Samarinda',
                'kecamatan' => 'Sungai Kunjang',
                'desa' => 'Loa Bakung',
                'kode_pos' => '75123',
                'latitude' => -0.5021,
                'longitude' => 117.1536,
                'status_tanah' => 'dijual',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0020',
                'ns' => 'NS-2026-000020',
                'name' => 'Andreas Pello',
                'luas_tanah' => '140 m2',
                'jenis_sertifikat' => 'HGB',
                'tanggal_terbit' => '2021-10-11',
                'masa_berlaku' => '2041-10-11',
                'alamat' => 'Jl. Boulevard No. 8',
                'provinsi' => 'Sulawesi Utara',
                'kabupaten' => 'Manado',
                'kecamatan' => 'Wenang',
                'desa' => 'Pinaesaan',
                'kode_pos' => '95111',
                'latitude' => 1.4748,
                'longitude' => 124.8421,
                'status_tanah' => 'aktif',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0021',
                'ns' => 'NS-2026-000021',
                'name' => 'Rizky Ramadhan',
                'luas_tanah' => '205 m2',
                'jenis_sertifikat' => 'SHM',
                'tanggal_terbit' => '2019-01-25',
                'masa_berlaku' => null,
                'alamat' => 'Jl. AP Pettarani No. 12',
                'provinsi' => 'Sulawesi Selatan',
                'kabupaten' => 'Makassar',
                'kecamatan' => 'Panakkukang',
                'desa' => 'Masale',
                'kode_pos' => '90231',
                'latitude' => -5.1477,
                'longitude' => 119.4327,
                'status_tanah' => 'aktif',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0022',
                'ns' => 'NS-2026-000022',
                'name' => 'Yuliana Tammu',
                'luas_tanah' => '175 m2',
                'jenis_sertifikat' => 'HP',
                'tanggal_terbit' => '2020-03-09',
                'masa_berlaku' => '2030-03-09',
                'alamat' => 'Jl. Yos Sudarso No. 4',
                'provinsi' => 'Sulawesi Tengah',
                'kabupaten' => 'Palu',
                'kecamatan' => 'Palu Timur',
                'desa' => 'Lolu Selatan',
                'kode_pos' => '94111',
                'latitude' => -0.9003,
                'longitude' => 119.8770,
                'status_tanah' => 'sengketa',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0023',
                'ns' => 'NS-2026-000023',
                'name' => 'Darmawan Yusuf',
                'luas_tanah' => '265 m2',
                'jenis_sertifikat' => 'SHM',
                'tanggal_terbit' => '2017-06-01',
                'masa_berlaku' => null,
                'alamat' => 'Jl. Pattimura No. 20',
                'provinsi' => 'Maluku',
                'kabupaten' => 'Ambon',
                'kecamatan' => 'Sirimau',
                'desa' => 'Uritetu',
                'kode_pos' => '97124',
                'latitude' => -3.6954,
                'longitude' => 128.1814,
                'status_tanah' => 'aktif',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0024',
                'ns' => 'NS-2026-000024',
                'name' => 'Eka Lestari',
                'luas_tanah' => '155 m2',
                'jenis_sertifikat' => 'HGB',
                'tanggal_terbit' => '2022-05-16',
                'masa_berlaku' => '2042-05-16',
                'alamat' => 'Jl. Trikora No. 7',
                'provinsi' => 'Papua',
                'kabupaten' => 'Jayapura',
                'kecamatan' => 'Jayapura Utara',
                'desa' => 'Gurabesi',
                'kode_pos' => '99111',
                'latitude' => -2.5407,
                'longitude' => 140.7130,
                'status_tanah' => 'aktif',
                'link_map' => null,
            ],
            [
                'kode_tanah' => 'TN-0025',
                'ns' => 'NS-2026-000025',
                'name' => 'Fajar Maulana',
                'luas_tanah' => '390 m2',
                'jenis_sertifikat' => 'HGU',
                'tanggal_terbit' => '2014-10-10',
                'masa_berlaku' => '2044-10-10',
                'alamat' => 'Kawasan Pertanian Blok D',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Bandar Lampung',
                'kecamatan' => 'Tanjungkarang Timur',
                'desa' => 'Keteguhan',
                'kode_pos' => '35125',
                'latitude' => -5.4294,
                'longitude' => 105.2625,
                'status_tanah' => 'dijual',
                'link_map' => null,
            ],
            
        ];

        foreach ($items as $item) {
            Tanah::updateOrCreate(
                ['kode_tanah' => $item['kode_tanah']],
                $item
            );
        }
    }
}
